Sunny-window/JobBingSoo

job/src/main/java/com/bingsoo/job/entity/Application.java, job/src/main/java/com/bingsoo/job/entity/Certificate.java, job/src/main/java/com/bingsoo/job/entity/Cs_reply.java, job/src/main/java/com/bingsoo/job/entity/FAQ.java, job/src/main/java/com/bingsoo/job/entity/Subscribe.java
=> 엔티티 수정후 커밋

job/src/main/java/com/bingsoo/job/entity/Company.java, job/src/main/java/com/bingsoo/job/entity/Cs.java, job/src/main/java/com/bingsoo/job/entity/Member.java, job/src/main/java/com/bingsoo/job/entity/Notice.java, job/src/main/java/com/bingsoo/job/entity/StarPoint.java, job/src/main/java/com/bingsoo/job/entity/Subscribe.java
=> 엔티티 수정후 커밋2

job-view/src/main/java/com/bingsoo/job_view/controller/RedbeanController.java, job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java
=> mypage작성중 커밋

job-view/src/main/java/com/bingsoo/job_view/controller/IceController.java, job-view/src/main/java/com/bingsoo/job_view/controller/RedbeanController.java, job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/entity/Resume.java, job/src/main/java/com/bingsoo/job/repository/RedBeanRepository.java, job/src/main/java/com/bingsoo/job/repository/ResumeRepository.java
=> main 한페이지 기능구현 중 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java
=> 마이페이지, 레드빈 컨트롤러 수정후 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java
=> 마이페이지 재작업중 커밋

job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/repository/CareerRepository.java, job/src/main/java/com/bingsoo/job/repository/CompanyRepository.java, job/src/main/java/com/bingsoo/job/repository/Desired_areaRepository.java, job/src/main/java/com/bingsoo/job/repository/Desired_industryRepository.java
=> 레파지토리 오류 수정후 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/dto/ResumeDto.java, job/src/main/java/com/bingsoo/job/repository/CertificateRepository.java
=> DTO작업중 커밋2

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/dto/ResumeDto.java, job/src/main/java/com/bingsoo/job/repository/Cover_letterRepository.java
=> 이력서 수정중 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java
=> 이력서기능 파일추가 및 썸네일 제외 구현후 커밋

job-view/src/main/resources/templates/cs/cs_detail.html, job-view/src/main/resources/templates/cs/cs_regist_form.html, job/src/main/java/com/bingsoo/job/controller/CsController.java, job/src/main/java/com/bingsoo/job/jwtToken/JWTUtil.java
=> jwt / getUsername(), getRole() 메서드 생성

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/repository/ResumeRepository.java
=> 이력서 수정 추가기능 구현중 커밋

job-view/src/main/java/com/bingsoo/job_view/controller/RedbeanController.java, job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/repository/ResumeRepository.java
=> 컨트롤러 url redbean통일후 커밋

job-view/src/main/resources/templates/manager/managerLogin.html, job-view/src/main/resources/templates/manager/youtubeplayer.html
=> 동영상 재생 플레이어 파괴 함수 수정

job-view/src/main/resources/templates/cs/cs_detail.html, job-view/src/main/resources/templates/cs/cs_list.html, job-view/src/main/resources/templates/sub/footer.html, job-view/src/main/resources/templates/sub/header.html, job-view/src/main/resources/templates/sub/notice.html, job/src/main/java/com/bingsoo/job/controller/SubController.java
알림 리스트 / 로그인된 해당 사용자에 맞게
마이페이지 클릭 시 기업회원은 기업페이지로 구직 회원은 구직자 페이지로 이동 구현
=> 알림 리스트, 고객센터 list css 오류 수정,

job-view/src/main/resources/templates/red_bean/mypage4.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/dto/FavoriteForNameDto.java, job/src/main/java/com/bingsoo/job/dto/SubscribeForNameDto.java, job/src/main/java/com/bingsoo/job/entity/Certificate.java, job/src/main/java/com/bingsoo/job/repository/CertificateRepository.java, job/src/main/java/com/bingsoo/job/repository/FavoriteRepository.java, job/src/main/java/com/bingsoo/job/repository/SubscribeRepository.java
정보수정 기능, 관심기업, 스크랩 목록 기능 마무리중 커밋
=> 정보수정 기능, 관심기업, 스크랩 목록 기능 마무리중 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java
=> 이력서등록 90프로 완료후 커밋

job-view/src/main/resources/templates/manager/ai.html
AI 분석 공고분석 및 전체 분석 FEAT.로딩 속도 느림
=> AI 분석 공고분석 및 전체 분석 FEAT.로딩 속도 느림

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/repository/CareerRepository.java, job/src/main/java/com/bingsoo/job/repository/Desired_areaRepository.java
=> 관심기업 스크랩공고 수정후 커밋

job-view/src/main/resources/templates/red_bean/mypage.html, job/src/main/java/com/bingsoo/job/controller/RedbeanController.java, job/src/main/java/com/bingsoo/job/dto/SubscribeForNameDto.java
=> 관심기업 리스트로 이동 입사지원 이동 완성후 커밋
